az k8sconfiguration create \
        --resource-group AzureArcK8s \
        --cluster-name AzureArc-gkev2 \
        --name team-a \
        --operator-instance-name team-a \
        --operator-namespace team-a \
        --operator-params '--git-readonly --sync-garbage-collection' \
        --enable-helm-operator \
        --helm-operator-chart-version 0.6.0 \
        --helm-operator-chart-values '--set helm.versions=v3' \
        --repository-url https://github.com/slack/team-config.git
		    --scope cluster --cluster-type connectedClusters
